### ISSUE TITLE
Documentation for the serial protocol

### ISSUE THREAD

**Issue by abhas** [Protocentral/HealthyPi#2]
I see that the HealthyPi communicates with the Raspberry Pi using a serial protocol. But the only way to understand how this happens would be to study the Processing source code. If you could share any documentation of the serial protocol, that would be very helpful in using the board to gather and store metrics using time-series databases, for example. Or just write some simple C or Python code to understand how the board works.

**Comment by awhitchurch** [comment]
We will document the protocol as well, but for now you can check the trasnmit protocol format in the following code:
 
https://github.com/Protocentral/HealthyPi/blob/master/firmware/src/main.c
